---
title: "Get Risk Free and Index Data"
author: "Pedro Teles"
date: "04/04/2022"
output: html_document
---

# Pacotes R

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(reticulate)
library(tidyverse)
library(xts)
library(PerformanceAnalytics)
library(lubridate)
```

# Pacotes Python

```{python}
import requests
import pandas as pd
```

# Dados IBRX e CDI

## IBRX

```{python}
# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBXX.SA&outputsize=full&apikey=TJDXT6P3GL8PGTNC'
r = requests.get(url)
ibrx = r.json()

datas = []
preco = []
for key in ibrx['Time Series (Daily)']:
    datas.append(key)
    preco.append(ibrx['Time Series (Daily)'][key]['4. close'])
    
preco_ibrx = pd.DataFrame({'Data': datas, 'IBX': preco})
preco_ibrx["IBX"] = pd.to_numeric(preco_ibrx["IBX"])
preco_ibrx["Data"] = pd.to_datetime(preco_ibrx["Data"])
preco_ibrx["Data"] = preco_ibrx["Data"].dt.strftime("%Y-%m-%d")
preco_ibrx.head()
```

## CDI

```{python}
def consulta_bc(codigo_bcb):
    url = 'http://api.bcb.gov.br/dados/serie/bcdata.sgs.{}/dados?formato=json'.format(codigo_bcb)
    df = pd.read_json(url)
    df['data'] = pd.to_datetime(df['data'], dayfirst=True)
    df.set_index('data', inplace=True)
    return df   
  
cdi = consulta_bc(12)
cdi_acumulado = (1 + cdi[cdi.index >= '2010-01-01'] / 100).cumprod()

d = {'Data': cdi_acumulado.index.strftime("%Y-%m-%d"), 'CDI': cdi_acumulado['valor'].tolist()}
cdi = pd.DataFrame(data=d)
```

## Risk Free Nefin

```{python}
rf_nefin = pd.read_excel('http://nefin.com.br/resources/risk_factors/Risk_Free.xls')
```

## Transformação em variáveis do R

```{r}
# Passamos as variaveis para o R
preco_ibrx <- py$preco_ibrx
rf_nefin <- py$rf_nefin

# Preparamos os dados de risk free para o merge com os dados do IBX
rf_nefin$Data <- make_date(rf_nefin$year, rf_nefin$month, rf_nefin$day)
rf_nefin$Risk_free <- cumprod(rf_nefin$Risk_free + 1) - 1
rf_nefin <- rf_nefin %>% dplyr::select(Data, Risk_free)

# Filtramos o IBX para termos apenas o periodo desejado
preco_ibrx$Data <- as.Date(preco_ibrx$Data)
preco_ibrx <- preco_ibrx %>% dplyr::filter(Data > '2008-12-31' & Data <= '2021-12-31')

# Juntamos as duas bases de dados
ind_rf <- merge(preco_ibrx, rf_nefin, by = 'Data', all.x = TRUE)

# Calculamos o retorno diario da tx livre de risco e do ibx
ind_rf$ret_ibx <- append(NA, diff(ind_rf$IBX)/ind_rf$IBX[-length(ind_rf$IBX)])
ind_rf$ret_rf <- append(NA, diff(ind_rf$Risk_free)/ind_rf$Risk_free[-length(ind_rf$Risk_free)])

# Selecionamos apenas as colunas de interesse
ind_rf <- ind_rf %>% dplyr::select(Data, ret_ibx, ret_rf)
ind_rf <- ind_rf[-1, ]

# Eliminamos as variaveis que nao sao mais necessarias
rm(rf_nefin, preco_ibrx)
```